### ISSUE TITLE
Error on Cloning Repo on Windows: Invalid Path in '.editorconfig ' File

### ISSUE THREAD

**Issue by mrjoechen** [mori-atsushi/kotlin-cacheable#19]
### Description

I encountered an issue when trying to clone the repository on a Windows system. The operation fails with the following error message: `error: invalid path '.editorconfig '`. It seems that the path or filename for the `.editorconfig` file is not compatible with Windows filesystem constraints.

### Steps to Reproduce

1. Attempt to clone the repository on a Windows machine using Git.
2. Observe the error during the cloning process.

### Actual Behavior

The cloning process fails with an error message indicating an invalid path for the `.editorconfig ` file.

### Possible Cause

The issue might be due to the filename `.editorconfig` having trailing spaces or characters that are not supported by the Windows filesystem.

### Environment

- OS: Windows 11
- Git version: git version 2.40.0.windows.1

### Additional Information

This issue may prevent Windows users from cloning the repository successfully. Adjusting the file name or path to be Windows-compatible might resolve the issue.

Thank you for looking into this matter.

Best regards,
Joe Chen

**Comment by mori-atsushi** [comment]
Thank you for your detailed report.
I fixed this in #20
